logger:

ota:
  - platform: esphome
    password: !secret esp_ota_password

debug:
  update_interval: 5s

web_server:
  port: 80
  version: 3

captive_portal:

time:
  - platform: sntp
    id: sntp_time
    timezone: Europe/Kyiv
