primary_wifi_ssid: "primary_wifi_ssid"
primary_wifi_password: "11111111"

alternative_wifi_ssid: "alternative_wifi_ssid"
alternative_wifi_password: "22222222"

fallback_ap_password: "33333333"
esp_ota_password: "44444444"

esp_cam_01_key: "1234567890"

